//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyShopThoiTrang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDN
    {
        public int MaHDN { get; set; }
        public string MaNV { get; set; }
        public string MaNCC { get; set; }
        public string MaSP { get; set; }
        public string NgayNhap { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> DonGia { get; set; }
    
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
