//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyShopThoiTrang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenMai
    {
        public string MaKM { get; set; }
        public string TenSPKM { get; set; }
        public Nullable<int> GiaKM { get; set; }
        public string Anh { get; set; }
        public Nullable<int> giamgia { get; set; }
        public string MaSP { get; set; }
        public string NgayBD { get; set; }
        public string NgyKT { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
